name: CI Workflow
on:
    push:
        branches:
            - main
            - feature/*
    pull_request:
        branches:
            - main
            - feature/*
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Building and linting
              run: npm run build
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test
            - name: Upload test report
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: test-report
                path: reports/*
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Ec2 instance
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script:
                    cd ~/github-actions-demo
                    git pull origin main
                    npm install
                    pm2 restart app.js


